require_relative './bank/serializer'
require_relative './bank/models/account'
require_relative './bank/serializers/account_serializer'
require_relative './bank/models/customer'
require_relative './bank/models/employee'
