require_relative './bank/models/account'
require_relative './bank/models/customer'
require_relative './bank/models/product'
require_relative './bank/models/product_type'
require_relative './bank/models/employee'
