default: &default
  encoding: utf8
  pool: 5

development:
  <<: *default
  adapter: mysql2
  database: bank

test:
  <<: *default
  adapter: mysql2
  database: bank_test

production:
  <<: *default
  adapter: postgresql
  database: bank_production
  username: bank
  password: <%= ENV['BANK_DATABASE_PASSWORD'] %>
