default: &default
  encoding: utf8
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: employees

test:
  <<: *default
  database: employees_test

production:
  <<: *default
  adapter: postgresql
  database: employees_production
  username: employees
  password: <%= ENV['EMPLOYEES_DATABASE_PASSWORD'] %>
